/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth.github'
import { Route as ApiProjectsProjectIdInfraPrRouteImport } from './routes/api/projects.$projectId.infra-pr'
import { Route as ApiProjectsProjectIdArchiveRouteImport } from './routes/api/projects.$projectId.archive'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth.github.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdInfraPrRoute =
  ApiProjectsProjectIdInfraPrRouteImport.update({
    id: '/$projectId/infra-pr',
    path: '/$projectId/infra-pr',
    getParentRoute: () => ApiProjectsRoute,
  } as any)
const ApiProjectsProjectIdArchiveRoute =
  ApiProjectsProjectIdArchiveRouteImport.update({
    id: '/$projectId/archive',
    path: '/$projectId/archive',
    getParentRoute: () => ApiProjectsRoute,
  } as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/infra-pr': typeof ApiProjectsProjectIdInfraPrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/infra-pr': typeof ApiProjectsProjectIdInfraPrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/infra-pr': typeof ApiProjectsProjectIdInfraPrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/projects'
    | '/api/auth/github'
    | '/api/auth/github/callback'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/infra-pr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/projects'
    | '/api/auth/github'
    | '/api/auth/github/callback'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/infra-pr'
  id:
    | '__root__'
    | '/'
    | '/api/projects'
    | '/api/auth/github'
    | '/api/auth/github/callback'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/infra-pr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/infra-pr': {
      id: '/api/projects/$projectId/infra-pr'
      path: '/$projectId/infra-pr'
      fullPath: '/api/projects/$projectId/infra-pr'
      preLoaderRoute: typeof ApiProjectsProjectIdInfraPrRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/projects/$projectId/archive': {
      id: '/api/projects/$projectId/archive'
      path: '/$projectId/archive'
      fullPath: '/api/projects/$projectId/archive'
      preLoaderRoute: typeof ApiProjectsProjectIdArchiveRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
  }
}

interface ApiProjectsRouteChildren {
  ApiProjectsProjectIdArchiveRoute: typeof ApiProjectsProjectIdArchiveRoute
  ApiProjectsProjectIdInfraPrRoute: typeof ApiProjectsProjectIdInfraPrRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsProjectIdArchiveRoute: ApiProjectsProjectIdArchiveRoute,
  ApiProjectsProjectIdInfraPrRoute: ApiProjectsProjectIdInfraPrRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
